### ISSUE TITLE
Make all PRs Black adherent 

### ISSUE THREAD

**Issue by archisha-chandel** [mozilla/PRESC#103]
As mentioned in the [Contribution guidelines](https://github.com/mozilla/PRESC#contribution-guidelines) :
Code formatting guidelines should strinctly adhere to [Python Black](https://pypi.org/project/black/) formatting guidelines.

Now, sometimes the contributors forget to ensure that the above is followed. To reduce the efforts while making sure the required code formatting is followed, adding Python Black as a pre-commit hook would make things easier.

**Comment by tab1tha** [comment]
Thank you for this @archisha-chandel
