### ISSUE TITLE
[Outreachy applications] ** PLEASE READ ** Updates to PR submission deadlines and review expectations!

### ISSUE THREAD

**Issue by mlopatka** [mozilla/PRESC#117]
Some of you have reached out to us regarding the closure of the repo to new contributors and the long delays in getting outstanding PRs reviewed. We want to be fair and considerate of all of your excellent work, but we also have to be realistic. We can not keep up with the volume of PRs and maintain a meaningful level of feedback.

- **Regarding new contributors with existing work:** In order to allow contributors who started working on a PR before we announced the project closed, we will allow a 2 day extension (until Wednesday, March 25th 20:00 GMT (UTC+0)). If you have work **that was already started before today** you can submit a [WIP] PR before that time and it will get reviewed. We will be verifying commit timestamps to treat this as a strict deadline. 
- **Between Wednesday March 25th and Monday March 30th** We ask that NO ONE SUBMIT PRs to the repo during this time. This will allow @dzeber and I time to clear the current queue of outstanding PRs, ensuring that every applicant gets a chance for feedback before the final week of applications. 
- **Between Monday March 30th and April 7th** Any PRs submitted in this period can be considered as part of candidates' final application (to be submitted via the process specified on the outreachy project page), however, **we can not guarantee that any of these PRs will be reviewed before the application deadline!** I have created the `post-closure-pr` label (see this issue for example) that will help us triage contributions that are submitted between 30-Mar and 07-Apr. 

Thank you all once again for your enthusiasm, excellent communication, great work, and for contributing to open source. Apologies for the bumps along the way with this project, we are doing our absolute best.

**Comment by mlopatka** [comment]
@mhmohona
@ssempervirens
@Sidrah-Madiha
@shubhank-saxena
@swatik718
@shashigharti
@anujaagarwal
@hammedb197
@Anukriti12
@shreyagupta30
@neozenweb
@janvi04
@dzeber
@mlopatka
@tab1tha
@AghaSaad04
@garvita-jain
@shailzaa
@TaimurAzhar
@Soniyanayak51
@dwvicy
@ebonnecab
@dzekem
@arizzogithub
@Sumangrewal
@rishilss99
@KPoornima
@abbasidaniyal
@aakankshadhurandhar
@KaairaGupta
@alberginia_gitlab
@Clare-Joyce
@elie-wanko
@SanchiMittal
@shiza16
@archisha-chandel
@Knight_rider_gitlab
@silvererudite
@blancadesal
@ClaraOdiri
@maxtastu
@shristi428
@Bolaji61
@RishikaBhatia17
@lauramurphy12
@jasmineflorencio
@Addi-11
@pratyush-ragini
@ubongjoshua
@asthad16
@SaumyaSinghal
@Simmranvermaa_twitter
@Herron62734675_twitter
@lalapupa
@ishagarg06
@NitiKaur
@o_feranmi__twitter
@Artemis-2
@theOpetunde
@namrathagopalabhatla
@yamini27
@urvigodha
@smritisingh26
@tasbihaasim
@NodiraIbrogimova

**Comment by asthad16** [comment]
i have updated  requested changes in my PR.
#26

**Comment by KaairaGupta** [comment]
@mlopatka can we make changes to the PR which we submitted before in this 25th to 30th period?

**Comment by BBimie** [comment]
I have new commits in my fork but I have been unable to make pull requests.
