### ISSUE TITLE
Prototyping for conditional feature distributions

### ISSUE THREAD

**Issue by dzeber** [mozilla/PRESC#194]
Test out the [conditional feature distributions](https://github.com/mozilla/PRESC/blob/master/docs/ROADMAP.md#conditional-feature-distributions) in a notebook using the implementation from #193. These should be run on two different dataset/model pairs.

**Comment by alberginia** [comment]
I implemented this one for my Outreachy application:
https://github.com/mozilla/PRESC-Outreachy-archive/blob/master/dev/alberginia/alberginia_issue7_3datasets.ipynb

**Comment by dzeber** [comment]
Replaced by #250
