### ISSUE TITLE
[Outreachy applications] Traversal of the space of cross-validation folds

### ISSUE THREAD

**Issue by dzeber** [mozilla/PRESC#4]
Similarly to #3, we want to investigate how much the performance score computed using cross-validation depends on the number of folds. Eg. how would our performance estimate change if we used 10-fold rather than 5-fold?

Write a function that takes a scikit-learn estimator and a dataset, and computes an evaluation metric using repeated K-fold cross-validation over a grid of K values from 1 to n. It should output a table of K with the average metric value across the folds, one for each repeat.

**Comment by asthad16** [comment]
i am working on this issue.

**Comment by asthad16** [comment]
i have submitted a PR #123 that mentions the issue #4 .please review it.
