### ISSUE TITLE
[Outreachy applications] Calibration plot

### ISSUE THREAD

**Issue by dzeber** [mozilla/PRESC#5]
A calibration plot assesses how well the predicted class probabilities match the actual rate of occurrence in the dataset.

Write a function to create a calibration plot given one or more binary classifiers and a test set. For each model it would compute predicted probabilities for each test datapoint. These probability values should then be binned according to a scheme (eg. intervals of 10%), and the observed occurrence rate can be computed as the proportion of true positive class samples out of all samples in each bin. The plot then displays the observed occurrence rates vs the bin midpoints for each model.

**Comment by Soniyanayak51** [comment]
@dzeber I would like to try this.

**Comment by dzekem** [comment]
I have sent a pull request for this issue.

**Comment by dzekem** [comment]
Also working on this issue.
