### ISSUE TITLE
[Outreachy applications] Visualization for misclassifications

### ISSUE THREAD

**Issue by dzeber** [mozilla/PRESC#7]
Misclassifications can reveal a lot about the boundaries of performance of a classifier. Develop a visualization that helps dig into misclassified datapoints in the test set. A simple approach for a binary classifier would be to plot a histogram of the predicted class probabilities across the misclassified test samples in each class.

**Comment by KaairaGupta** [comment]
This issue seems interesting. May I be assigned this?

**Comment by dzeber** [comment]
You're welcome to work on it and submit a contribution! We're not assigning issues currently to allow people to bring multiple perspectives or approaches to these questions.

**Comment by shristi428** [comment]
how can we contribute in the project should we PR then you assign us task ?

**Comment by dzeber** [comment]
@shristi428 You can submit a PR referencing the issue you worked on.

**Comment by namrathagopalabhatla** [comment]
Hey @dzeber! What dataset do we use to test out our code?

**Comment by dzeber** [comment]
@namrathagopalabhatla whichever you like. It might be a good start to use the same data & model you used for #2.
