### ISSUE TITLE
[Outreachy applications] Covariate Shift

### ISSUE THREAD

**Issue by archisha-chandel** [mozilla/PRESC#78]
As said in issue #3, a function has been written to check the evaluation metric for a model when train-test split ratio is varied from 0.0- 1.0. But there are cases where we cannot just randomly decide the split ratio on the basis on evaluation metric as the metric does not improve beyond a certain point. Example: [data set](https://www.kaggle.com/c/porto-seguro-safe-driver-prediction/data) based on predicting the probability that an auto insurance policy holder files a claim by Porto Seguro has data which has covariate shift. For this data using the regular methods does not yield a good evaluation metric score.

Propose a solution to detect and handle covariates in the data. The above mentioned data or any other can be used for implementation which may or may not have covariates.
**Note: This issue has been created to provide a solution to issue #3 which has an exception of not dealing with data that has covariate shift.**

Covariate Shift: It refers to a situation where predictor variables have different characteristics (distribution) in train and test data. So our model is unable to predict well on the test data as it has been trained on a certain set of feature characteristics which are different from test data. 

![image](https://user-images.githubusercontent.com/47753303/76925232-c12aa200-68fe-11ea-9e8c-b2e2572f0192.png)

**Comment by namrathagopalabhatla** [comment]
Are we supposed to work on this issue?

**Comment by mlopatka** [comment]
You are free to work on this issue, but it is not required or expected.
You can also spend the next days finalizing your outreachy application.
