### ISSUE TITLE
[Outreachy applications] Comparing test sample classifications between models

### ISSUE THREAD

**Issue by dzeber** [mozilla/PRESC#9]
To delve further into model performance comparisons, it would be interesting to compare the classification results (ie. predicted probabilities) for individual datapoints. This would also help to understand misclassifications.

Develop a visualization to compare predicted class probabilities across models for binary classifiers. For example, this could present a histogram of the difference in predicted probabilities between the two models across all training samples. Misclassifications under either model could also be split out.

**Comment by tab1tha** [comment]
I'm working on this.
